#!/usr/bin/env bash
# Configure a utf firewall to block al incoming trafic
# except for TCP ports 22, 80, 443

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
