#!/usr/bin/env bash
# ssh_config

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/id_rsa
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    HostName 100.26.142.9
    User ubuntu
