#!/usr/bin/env bash
# ssh_config

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    HostName 54.209.117.94
    User ubuntu
